### ISSUE TITLE
connect grids

### ISSUE THREAD

**Issue by Roywcm** [ducksboard/gridster.js#133]
Hi,

Is it possible to connect two grids?
So, you can drag and drop a widget from one to the other grid?

I'll hope this is possible! Really need this.

Roy

**Comment by FRickReich** [comment]
splendid idea! +1

**Comment by tuimz** [comment]
+1 Would be really great!

**Comment by lukju** [comment]
+1
would be very useful, because in a gridster with more than a couple of widgets the drag-and-drop game becomes difficult and is similar to a puzzle.
using multiple gridsters with the possibility to drag and drop widgets from one gridster to the other would solve this issue.
i guess the crew who developed the Window 8 start screen had exactly the same thoughts...

**Comment by nuwanbando** [comment]
+1 great idea

**Comment by JoschaP** [comment]
+1

**Comment by saenzramiro** [comment]
+1

**Comment by JoschaP** [comment]
+1

**Comment by jmaag** [comment]
+1

**Comment by rcesare** [comment]
+1

**Comment by bpbhat77** [comment]
+1

**Comment by dustinbolton** [comment]
+1

**Comment by vieron** [comment]
Duplicate of #68
