### ISSUE TITLE
Problem when resizing and adding new widgets 

### ISSUE THREAD

**Issue by thoma202** [ducksboard/gridster.js#196]
Hi, 

I tried this on the demo version. 

Follow this : 
$widget = gridster.add_widget('<li></li>', 4, 3)
$widget =gridster.resize_widget($widget , 6, 1)
gridster.add_widget('<li></li>', 1, 1);
gridster.add_widget('<li></li>', 1, 1);
gridster.add_widget('<li></li>', 1, 1);

When you do that, then the grid get broken and new widget go to the right and not as expected in the grid !

**Comment by MartinWeise** [comment]
I think this is caused by the auto placement from gridster.
Btw you need HTML Markup in the gridster.add_widget("<li>Markup here</li>", sizex, sizey); - function.

So, when the grid registers the widget, you need to change the "data-col"-attribute. Gridster.js does the rest for you (replacing immediatly)

Code would be like:

var gridster = $(".gridster ul").gridster().data('gridster');
$('.trigger').click(function() {
     var e = gridster.add_widget('<li>My new widget</li>', 1, 1); // (html, sizex, sizey)
     e.data('col',3); // (attr, column_widget_should_be)
});

Untested, but it should work,
Have a nice evening from Austria!

**Comment by baiiko** [comment]
Hi,

I have same bugs.

With the settings, i can change the size widget. After my resize the gridmap is different.

# Steps :
1. I just add two widgets.
2. After, i change the size of first widget to max-width.

# Screens :

**before :**

![image](https://f.cloud.github.com/assets/3129221/787228/30b42836-ead4-11e2-8478-96dd11102269.png)

**after :**

![image](https://f.cloud.github.com/assets/3129221/787224/202dd660-ead4-11e2-8ee8-0a461eb45ba9.png)

**Comment by vieron** [comment]
Fixed here 195295be
