### ISSUE TITLE
Drag multiple blocks at once

### ISSUE THREAD

**Issue by willian-pestana** [ducksboard/gridster.js#313]
Hello,

I'm using the latest version of this plug-in and think it's amazing.
I was wondering, there is a way to drag multiples blocks at once?

I'm thinking on create a user interface using Gridster. I want it to be user-friendly, that's why I'm asking this question.

**Comment by willian-pestana** [comment]
Calm down, I just asked, there's no need to answer like this. A 'NO' would be better. I was just thinking if wasn't possible to select more than one block before start dragging it. 

Think like this: you can drag one icon on your desktop, but you also can select more than one and drag them. I have only one mice and it's possible, you can't do it?

Please, if you can't answer properly, don't answer it.

**Comment by ch1ago** [comment]
OK, I'm sorry that was too fast.
I believe this feature is counter-intuitive to how users behave.
It could be conflicting to some devices since the SO and the Browser already hold some muti-touch behaviors.

Yes, I think it would be pretty cool to be able to group stuff together, or maybe just simply locking elements in their positions. :+1: 

But in the end I believe it would lead to internal conflicts and bugs. :disappointed: 

That's why I said no :-1: :disappointed:

**Comment by willian-pestana** [comment]
Yeah, you are right. Actually, I never believed that was possible.  The first time I thought about it, I wonder if I could create a '"receptacle". A place that could store blocks, then maybe I could drag just this receptacle. I thought on creating this, but I just have no time (or guts) for it.

**Comment by ch1ago** [comment]
we're evaluating using this gem for a project right now,
we're having this problem with it, that we wanted to have 2 different grids, so you can drag them between them,

but, here's the catch, the side-grid understand an element with a completely different CSS,
so it looks like the side-grid is a painting palette or the compact inventory bag
while the main grid is the canvas or the place they're actually for display.

but we still haven't reached a conclusion yet, because we're still evaluating other alternatives.

nonetheless, I believe one of the things that make this project popular is how many things it doesn't do, leaving extending it up to us.

**Comment by dustmoo** [comment]
I wouldn’t say it is impossible, but the way the library is currently written you would have to write quite a bit of custom code.   

Thanks,  

Dustin

**Comment by vieron** [comment]
Not easy with current gridster design. Take a look at [Packery](http://packery.metafizzy.co), it supports drag multiple blocks at time in multi-touch devices.
