### ISSUE TITLE
Issue with the added widgets

### ISSUE THREAD

**Issue by benjaryu** [ducksboard/gridster.js#35]
Hi,

I found something weird with the addition of new widgets. I created a resize button for my widgets, the button is inside the widget. It works very well with the preloaded widgets (in my html).

Here is a sample: http://jsfiddle.net/benjaryu/gd4tc/10/

However, when I add a widget with a resize button in it:

<pre>
<code>

  //add box
$('.addbox').click(function(){
gridster.add_widget('<li><div class="box"><div class="box-content">Test the menu HERE !!!</div><div class="menu"><div class="resizeme22"><a href="JavaScript:void(0);">resize me!</a></div></div></div></li>', 1, 1);
  });
</code>
</pre>

The resize button doesn't work in the new widget. How can I fix that ? 

Thanks :)
Regards,

Benjamin

PS: Btw, great job with gridster, I really love it!

**Comment by schadeck** [comment]
This is because you are using the `.click(function{})` instead of `.live('click',  function {})`, or better yet `.on('click', '.resize22', function {})`.  Since the new widgets are generated after the DOM was generated, the `.click()` will not be able to address them. Meanwhile live, and on have the ability to bind the event to the desired element:

http://jsfiddle.net/eB2Cs/

**Comment by benjaryu** [comment]
Thanks a lot for your help, it works like a charm ;)

**Comment by Dwtbc** [comment]
I have a button inside my added widget, that triggers a box to slide down.

But when added the box doesn't slide down.

http://jsfiddle.net/ygAV2/
