### ISSUE TITLE
"resize_widget" not working as it should

### ISSUE THREAD

**Issue by pmking** [ducksboard/gridster.js#83]
I'm trying to change the size of a widget. The problem is that the function:
<b>.resize_widget( $widget, [size_x], [size_y] )</b>
seems to have a real issue when  <i><b>size_x </b></i> is bigger than 6.

I've done several examples and it seems like ALWAYS the widget dissapears when  size-x > 6  !!

Does anyone knows why this is happening?
I've made an example showing this ssue:

http://jsfiddle.net/pmking/paDE7/

I would like to get this result.:
<a href="http://imgur.com/9GSeB"><img src="http://i.imgur.com/9GSeB.png" title="Hosted by imgur.com" alt="" /></a>

but instead of that, I'm getting this weird result:
<a href="http://imgur.com/29s6t"><img src="http://i.imgur.com/29s6t.png" alt="" title="Hosted by imgur.com" /></a>

**Comment by timatron** [comment]
can we see the setup of your gridster? do you have more than 6 columns?

**Comment by tyraeltong** [comment]
This is actually because you didn't set "max_size_x" and it's been default to 6, thus gridster.js only generate style for [data-size-x="6"], and then if your widget size_x goes beyond 6, there's no css apply to it, thus its width becomes 0px.

See my update to the jsFiddle: 

http://jsfiddle.net/paDE7/4/

**Comment by pmking** [comment]
Hi tyraeltong, 
You are right! I've just set the "max_size_x=20"  and now there's no problem at all...
Thank you so much for your  help.
