### ISSUE TITLE
Not working with jQuery 1.8.3?

### ISSUE THREAD

**Issue by ashishanand25** [ducksboard/gridster.js#99]
Hey guys,

It's working well with jQuery 1.7.2 but not with the newer 1.8.3 - could you confirm?
The elements display, but when you move them around, you cannot release it to drop it to a destination and it reverts back to the original state. (It works with jQuery 1.8.3 in FireFox but not in Chrome 23.0.xxxx). Can you confirm ?

**Comment by ashishanand25** [comment]
Anybody??

**Comment by dustmoo** [comment]
I have not had any trouble with 1.8.3.. did you check your console?

**Comment by danshryock** [comment]
I was experiencing the exact same symptoms, and I was also concerned that it may be related to using a different version of jQuery.  Luckily, that wasn't the case.

It turned out to be a timing issue.  If you try to initialize gridster before the DOM element is attached to the document, it will only function partially.  It will have difficulty detecting how many columns to render, and it will not be able to drop items into new locations, they just go back to where they were before.

I just waited to run $(elem).gridster({...}) until after my $(elem) was appended to the document and everything started working perfectly!
